# -*- coding: utf-8 -*-
# -*- mode: org -*-

#+TITLE: Le génie logiciel pour un ingénieur en science des données
#+AUTHOR: Kévin CAYE
#+LANGUAGE: fr

# reveal options: see https://github.com/yjwen/org-reveal
#+REVEAL_ROOT: http://cdn.jsdelivr.net/reveal.js/3.0.0/
#+REVEAL_TRANS: none
#+OPTIONS: reveal_center:nil
#+OPTIONS: reveal_width:1200 reveal_height:800
#+REVEAL_THEME: white
#+REVEAL_HLEVEL: 0 ## all header on same lvl
#+REVEAL_SPEED: fast
#+REVEAL_EXTRA_CSS: ./extra.css
#+REVEAL_EXTRA_JS: 

Objectif: montrer les différents cas de figure que j'ai rencontrer pour dans mon
expérience. Je ne veux pas etre exhaustif mais peut être que mon expérience
pourra vous aider dans des situations similaires.

Commencer par mon profile et mes attentes dans mon boulot. Présenter mes
expérience avec leur contexte, les problèmes et les solutions apporté. point
clée:
- développer des méthodes mathématiques (stage fin d'étude)
  - première erreur: le c++ c'est super rapide dont je dev en c++. chercher à
    optimiser trop tôt
  - j'itère sans faire de test: on sait rapidement plus ou on en ai ! Même quand
    on dev un prototype c'est pas pour de la production ! il faut faire des
    tests ! au moins sur le coeur algorithmique. Pas des test unitaires plutôt
    tester des situations.
- thèses: 
  - les model en data sciences
    - les données: idéal avoir 3 niveaux model génératif, model simulé mais plus
      compliqué, données réelles
  - la programmation en data science: fonctionnel
    - faire une comparaison d'un model implémenté en object et un en fonctionnel ?
  - La reproductibilité en science
- Schneider electric
  - devops
  - parler de ca: [[https://en.wikipedia.org/wiki/Cross-industry_standard_process_for_data_mining][Cross-industry standard process for data mining]]
  - parler de du TDD même pour les explorations: see [[https://github.com/drivendataorg/power-laws-cold-start/tree/80d612b3ab881647f5a8b6a13960e81985630dc0/1st%2520Place/team-member-a-execute-first#start-of-the-challenge][power-laws-cold-start]]
  - organization: trouver ca facon de fonctionner: montrer mon workflow. Comment
    mes dossiers sont organisé et les outils que j'utilise: git lfs pour les
    data + donnée intermediaire
- Remarques en vrac
  - la gestion du model est très importante ! 
  - avant c'est surtout les chercheurs qui avait des données
  - maintenant il y en a partout en industrie
  - la mesure de l'erreur est super important.
    - definir ce qu'on veut mesurer TODO
    - Pour ne pas se tromper il faut être rigoureux ! Et donc organiser, comment
      decouper le dataset ?
  - parler du piege des notebooks ! et du manque de test unitaire en phase
    d'exploration. 
*Plan*
- Definition des data science et de l'ingénieur en datascience (proposer ma
  définition), en particulier en industrie avec des examples. Donner aussi des
  exemples en science.
- Proposition d'un workflow.
- Définir les problématiques de chaque étapes et apporter une proposition de
  solutions et les outils utilisé.
- Conclusions et take away messages.
* TODO TODO                                                        :noexport:
Faire un peut en mode time line
- définir science des données
- sorti de l'ensimag: git et c++
- thèse: programmation fonctionnel
- prestation: mise en production par des web service
- present the service oriented Architechture: [[https://en.wikipedia.org/wiki/Service-oriented_architecture][wikipedia
]]  - Pourquoi on fait ca dans l'équipe AAI (présenter l'équipe AAI)
Expliquer à chaque fois les notions: c'est quoi et à quoi ca sert

* Mon parcourt
:LOGBOOK:
- Note taken on [2018-11-13 Tue 16:56] \\
  where to code come https://freefrontend.com/css-timelines/#horizontal-timelines
- Note taken on [2018-11-13 Tue 16:56] \\
  make an html iframe
:END:
#+BEGIN_EXPORT html
<section class="timeline">
  <ol>
    <li>
      <div>
        <time>1934</time> At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium
      </div>
    </li>
    <li>
      <div>
        <time>1937</time> Proin quam velit, efficitur vel neque vitae, rhoncus commodo mi. Suspendisse finibus mauris et bibendum molestie. Aenean ex augue, varius et pulvinar in, pretium non nisi.
      </div>
    </li>
    <li>
      <div>
        <time>1940</time> Proin iaculis, nibh eget efficitur varius, libero tellus porta dolor, at pulvinar tortor ex eget ligula. Integer eu dapibus arcu, sit amet sollicitudin eros.
      </div>
    </li>
    <li>
      <div>
        <time>1943</time> In mattis elit vitae odio posuere, nec maximus massa varius. Suspendisse varius volutpat mattis. Vestibulum id magna est.
      </div>
    </li>
    <li>
      <div>
        <time>1946</time> In mattis elit vitae odio posuere, nec maximus massa varius. Suspendisse varius volutpat mattis. Vestibulum id magna est.
      </div>
    </li>
    <li>
      <div>
        <time>1956</time> In mattis elit vitae odio posuere, nec maximus massa varius. Suspendisse varius volutpat mattis. Vestibulum id magna est.
      </div>
    </li>
    <li>
      <div>
        <time>1957</time> In mattis elit vitae odio posuere, nec maximus massa varius. Suspendisse varius volutpat mattis. Vestibulum id magna est.
      </div>
    </li>
    <li>
      <div>
        <time>1967</time> Aenean condimentum odio a bibendum rhoncus. Ut mauris felis, volutpat eget porta faucibus, euismod quis ante.
      </div>
    </li>
    <li>
      <div>
        <time>1977</time> Vestibulum porttitor lorem sed pharetra dignissim. Nulla maximus, dui a tristique iaculis, quam dolor convallis enim, non dignissim ligula ipsum a turpis.
      </div>
    </li>
    <li>
      <div>
        <time>1985</time> In mattis elit vitae odio posuere, nec maximus massa varius. Suspendisse varius volutpat mattis. Vestibulum id magna est.
      </div>
    </li>
    <li>
      <div>
        <time>2000</time> In mattis elit vitae odio posuere, nec maximus massa varius. Suspendisse varius volutpat mattis. Vestibulum id magna est.
      </div>
    </li>
    <li>
      <div>
        <time>2005</time> In mattis elit vitae odio posuere, nec maximus massa varius. Suspendisse varius volutpat mattis. Vestibulum id magna est.
      </div>
    </li>
    <li></li>
  </ol>
#+END_EXPORT
* La programmation orienté objet
* La programmation orienté objet
* La programmation fonctionnelle: Définition
:LOGBOOK:
- Note taken on [2018-10-26 Fri 15:58] \\
  read that https://stackoverflow.com/questions/4852251/is-there-a-software-engineering-methodology-for-functional-programming
:END:
- définir
- pourquoi c'est autant utilisé ?
- Vous faite du R ?
* La programmation fonctionnelle: 
* Intégration continue
